--- 
body: 
  - 
    attributes: 
      description: "A clear and concise description of what the problem is."
      label: "Problem you would like to solve"
      placeholder: "Example: I am always frustrated when [...]"
    id: problem-description
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Describe the solution you'd like to see implemented."
      label: "Proposed solution"
    id: solution-proposed
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "A clear and concise description of any alternative solutions or features you've considered."
      label: "Alternatives considered"
    id: alternatives
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "Add any other context or screenshots about the feature request here. For example, provide the execution platform you are operating on (Camunda 7, Camunda 8, ...)."
      label: "Additional context"
    id: additional-context
    type: textarea
    validations: 
      required: false
description: "Suggest an idea or general improvement."
labels: 
  - enhancement
name: "Feature request"
